databases:
  - name: socialsite
    databaseName: socialsite
    user: socialsite

services:
  - type: web
    name: socialsite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: socialsite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

