Here's the render.yaml file again:
services:
  - type: web
    name: socialsite
    runtime: ruby
    buildCommand: bundle install
    startCommand: rails s
    envVars:
      - key: RAILS_ENV
        value: production

databases:
  - name: socialdb
    type: postgresql

